name: Ubuntu_Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh
    - name: Setup 
      run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           cd ~
           git clone https://${{ secrets.EMAIL }}":${{ secrets.PASSWORD }}"@github.com/JamieHoSzeYui/jampp.git tools
           git clone --recurse-submodules https://github.com/erfanoabdi/firmware_extractor extract
           
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master

